nutgram:
  # The Telegram bot token
  token: '%env(string:NUTGRAM_TOKEN)%'

  # If true, the webhook mode validates the incoming IP range is from a Telegram server
  safe_mode: false

  # Extra or specific configuration
  config: [ ]

  # If the nutgram bundle should automatically load the routes from config/telegram.php
  routes: true
