services:

  SergiX44\NutgramBundle\DependencyInjection\Factory\NutgramFactory: ~

  SergiX44\NutgramBundle\NutgramConfigurator:
    autowire: true
    arguments: [ '%nutgram.config%' ]

  SergiX44\Nutgram\Nutgram:
    autowire: true
    public: true
    factory: [ '@SergiX44\NutgramBundle\DependencyInjection\Factory\NutgramFactory', 'createNutgram' ]
    arguments: [ '%nutgram.config%', '@service_container' ]
    configurator: [ '@SergiX44\NutgramBundle\NutgramConfigurator', 'configure' ]

  nutgram:
    alias: 'SergiX44\Nutgram\Nutgram'

  SergiX44\NutgramBundle\Console\:
    resource: '../src/Console/'
    autowire: true
    tags: [ 'console.command' ]
